export const siteTagMapTypes: Record<string, { en: string; "zh-CN": string }> = {
  agency: { en: "Agency", "zh-CN": "机构" },
  ai: { en: "AI", "zh-CN": "人工智能" },
  architecture: { en: "Architecture", "zh-CN": "建筑" },
  art: { en: "Art", "zh-CN": "艺术" },
  automotive: { en: "Automotive", "zh-CN": "汽车" },
  beauty_makeup: { en: "Beauty makeup", "zh-CN": "美妆" },
  communication: { en: "Communication", "zh-CN": "通信" },
  community: { en: "Community", "zh-CN": "社区" },
  crypto: { en: "Crypto", "zh-CN": "加密" },
  design: { en: "Design", "zh-CN": "设计" },
  desktop_app: { en: "Desktop App", "zh-CN": "桌面应用" },
  development: { en: "Development", "zh-CN": "开发" },
  dress: { en: "Dress", "zh-CN": "服饰" },
  digital_product: { en: "Digital Product", "zh-CN": "数字产品" },
  e_commerce: { en: "E-commerce", "zh-CN": "电子商务" },
  education: { en: "Education", "zh-CN": "教育" },
  event: { en: "Event", "zh-CN": "活动" },
  exhibition: { en: "Exhibition", "zh-CN": "展览" },
  fashion: { en: "Fashion", "zh-CN": "时尚" },
  finance: { en: "Finance", "zh-CN": "金融" },
  food_drink: { en: "Food & Drink", "zh-CN": "食品与饮料" },
  font: { en: "Font", "zh-CN": "字体" },
  furniture: { en: "Furniture", "zh-CN": "家具" },
  gaming: { en: "Gaming", "zh-CN": "游戏" },
  health: { en: "Health", "zh-CN": "健康" },
  hospitality: { en: "Hospitality", "zh-CN": "酒店业" },
  hr: { en: "HR", "zh-CN": "人资" },
  interior_design: { en: "Interior Design", "zh-CN": "室内设计" },
  landscaping: { en: "Landscaping", "zh-CN": "园林设计" },
  legal: { en: "Legal", "zh-CN": "法律" },
  literature: { en: "Literature", "zh-CN": "文学" },
  magazine: { en: "Magazine", "zh-CN": "杂志" },
  manufacturing: { en: "Manufacturing", "zh-CN": "制造" },
  marketing: { en: "Marketing", "zh-CN": "营销" },
  medicine: { en: "Medicine", "zh-CN": "医药" },
  mobile_app: { en: "Mobile App", "zh-CN": "移动应用" },
  motion: { en: "Motion", "zh-CN": "动效" },
  music: { en: "Music", "zh-CN": "音乐" },
  news: { en: "News", "zh-CN": "新闻" },
  nft: { en: "NFT", "zh-CN": "NFT" },
  personal: { en: "Personal", "zh-CN": "个人" },
  pet: { en: "Pet", "zh-CN": "宠物" },
  photography: { en: "Photography", "zh-CN": "摄影" },
  plugin: { en: "Plugin", "zh-CN": "插件" },
  podcast: { en: "Podcast", "zh-CN": "播客" },
  political: { en: "Political", "zh-CN": "政治" },
  portfolio: { en: "Portfolio", "zh-CN": "作品集" },
  product: { en: "Product", "zh-CN": "产品" },
  public_relations: { en: "Public relations", "zh-CN": "公关" },
  real_estate: { en: "Real Estate", "zh-CN": "房地产" },
  restaurant: { en: "Restaurant", "zh-CN": "餐厅" },
  saas: { en: "SaaS", "zh-CN": "SaaS" },
  science: { en: "Science", "zh-CN": "科学" },
  security: { en: "Security", "zh-CN": "安全" },
  sports: { en: "Sports", "zh-CN": "体育" },
  technology: { en: "Technology", "zh-CN": "科技" },
  travel: { en: "Travel", "zh-CN": "旅行" },
  web_app: { en: "Web App", "zh-CN": "Web应用" },
  web3: { en: "Web3", "zh-CN": "Web3" },
};

export const siteTagMapStyles = {
  "3d": { en: "3D", "zh-CN": "3D" },
  animation: { en: "Animation", "zh-CN": "动画" },
  audio: { en: "Audio", "zh-CN": "音频" },
  bento_grid: { en: "Bento Grid", "zh-CN": "便当网格" },
  big_background_image: { en: "Big Background Image", "zh-CN": "大背景图" },
  big_background_video: { en: "Big Background Video", "zh-CN": "大背景视频" },
  black_white: { en: "Black & White", "zh-CN": "黑白" },
  clean: { en: "Clean", "zh-CN": "简洁" },
  colorful: { en: "Colorful", "zh-CN": "五彩缤纷" },
  custom_cursor: { en: "Custom Cursor", "zh-CN": "自定义光标" },
  dark: { en: "Dark", "zh-CN": "暗色" },
  drag_drop: { en: "Drag & Drop", "zh-CN": "拖放" },
  fun: { en: "Fun", "zh-CN": "有趣" },
  gradient: { en: "Gradient", "zh-CN": "渐变" },
  grid: { en: "Grid", "zh-CN": "网格" },
  horizontal_layout: { en: "Horizontal Layout", "zh-CN": "水平布局" },
  horizontal_scrolling: { en: "Horizontal Scrolling", "zh-CN": "水平滚动" },
  illustrative: { en: "Illustrative", "zh-CN": "插画" },
  infinite_scroll: { en: "Infinite Scroll", "zh-CN": "无限滚动" },
  interactive: { en: "Interactive", "zh-CN": "交互式" },
  large_type: { en: "Large Type", "zh-CN": "大字体" },
  light: { en: "Light", "zh-CN": "亮色" },
  light_shadow: { en: "Light & Shadow", "zh-CN": "光影" },
  long_scrolling: { en: "Long Scrolling", "zh-CN": "长滚动" },
  masonry: { en: "Masonry", "zh-CN": "瀑布流" },
  minimal: { en: "Minimal", "zh-CN": "极简" },
  mimicry: { en: "Mimicry", "zh-CN": "拟物" },
  monochromatic: { en: "Monochromatic", "zh-CN": "单色调" },
  parallax: { en: "Parallax", "zh-CN": "视差滚动" },
  pastel: { en: "Pastel", "zh-CN": "粉彩" },
  retro: { en: "Retro", "zh-CN": "复古" },
  scrolling_animation: { en: "Scrolling Animation", "zh-CN": "滚动动效" },
  single_page: { en: "Single Page", "zh-CN": "单页" },
  small_type: { en: "Small Type", "zh-CN": "小字体" },
  transitions: { en: "Transitions", "zh-CN": "过渡效果" },
  typographic: { en: "Typographic", "zh-CN": "排版" },
  unusual_layout: { en: "Unusual Layout", "zh-CN": "非常规布局" },
  virtual_reality: { en: "Virtual Reality", "zh-CN": "虚拟现实" },
  webgl: { en: "WebGL", "zh-CN": "WebGL" },
};

export const siteTagMap: Record<string, { en: string; "zh-CN": string }> = {
  ...siteTagMapTypes,
  ...siteTagMapStyles,
};

export const siteTagKeys = Object.keys(siteTagMap);
