export const siteTagMapTypes = {
  agency: { en: "Agency", zh: "机构" },
  ai: { en: "AI", zh: "人工智能" },
  architecture: { en: "Architecture", zh: "建筑" },
  art: { en: "Art", zh: "艺术" },
  automotive: { en: "Automotive", zh: "汽车" },
  communication: { en: "Communication", zh: "通信" },
  community: { en: "Community", zh: "社区" },
  construction: { en: "Construction", zh: "建筑施工" },
  crypto: { en: "Crypto", zh: "加密货币" },
  design: { en: "Design", zh: "设计" },
  desktop_app: { en: "Desktop App", zh: "桌面应用" },
  development: { en: "Development", zh: "开发" },
  digital_product: { en: "Digital Product", zh: "数字产品" },
  e_commerce: { en: "E-commerce", zh: "电子商务" },
  education: { en: "Education", zh: "教育" },
  event: { en: "Event", zh: "活动" },
  exhibition: { en: "Exhibition", zh: "展览" },
  fashion: { en: "Fashion", zh: "时尚" },
  finance: { en: "Finance", zh: "金融" },
  food_drink: { en: "Food & Drink", zh: "食品与饮料" },
  furniture: { en: "Furniture", zh: "家具" },
  gaming: { en: "Gaming", zh: "游戏" },
  health: { en: "Health", zh: "健康" },
  hospitality: { en: "Hospitality", zh: "酒店业" },
  interior_design: { en: "Interior Design", zh: "室内设计" },
  landscaping: { en: "Landscaping", zh: "园林设计" },
  legal: { en: "Legal", zh: "法律" },
  literature: { en: "Literature", zh: "文学" },
  magazine: { en: "Magazine", zh: "杂志" },
  marketing: { en: "Marketing", zh: "营销" },
  mobile_app: { en: "Mobile App", zh: "移动应用" },
  motion: { en: "Motion", zh: "动效" },
  music: { en: "Music", zh: "音乐" },
  news: { en: "News", zh: "新闻" },
  nft: { en: "NFT", zh: "NFT" },
  personal: { en: "Personal", zh: "个人" },
  pet: { en: "Pet", zh: "宠物" },
  photography: { en: "Photography", zh: "摄影" },
  podcast: { en: "Podcast", zh: "播客" },
  political: { en: "Political", zh: "政治" },
  portfolio: { en: "Portfolio", zh: "作品集" },
  real_estate: { en: "Real Estate", zh: "房地产" },
  restaurant: { en: "Restaurant", zh: "餐厅" },
  saas: { en: "SaaS", zh: "SaaS" },
  science: { en: "Science", zh: "科学" },
  security: { en: "Security", zh: "安全" },
  sports: { en: "Sports", zh: "体育" },
  technology: { en: "Technology", zh: "科技" },
  travel: { en: "Travel", zh: "旅行" },
  web_app: { en: "Web App", zh: "Web应用" },
  web3: { en: "Web3", zh: "Web3" },
};

export const siteTagMapStyles = {
  "3d": { en: "3D", zh: "3D" },
  animation: { en: "Animation", zh: "动画" },
  audio: { en: "Audio", zh: "音频" },
  bento_grid: { en: "Bento Grid", zh: "便当网格" },
  big_background_image: { en: "Big Background Image", zh: "大背景图" },
  big_background_video: { en: "Big Background Video", zh: "大背景视频" },
  black_white: { en: "Black & White", zh: "黑白" },
  clean: { en: "Clean", zh: "简洁" },
  colorful: { en: "Colorful", zh: "五彩缤纷" },
  custom_cursor: { en: "Custom Cursor", zh: "自定义光标" },
  dark: { en: "Dark", zh: "暗色" },
  drag_drop: { en: "Drag & Drop", zh: "拖放" },
  fun: { en: "Fun", zh: "有趣" },
  gradient: { en: "Gradient", zh: "渐变" },
  grid: { en: "Grid", zh: "网格" },
  horizontal_layout: { en: "Horizontal Layout", zh: "水平布局" },
  horizontal_scrolling: { en: "Horizontal Scrolling", zh: "水平滚动" },
  illustrative: { en: "Illustrative", zh: "插花" },
  infinite_scroll: { en: "Infinite Scroll", zh: "无限滚动" },
  interactive: { en: "Interactive", zh: "交互式" },
  large_type: { en: "Large Type", zh: "大字体" },
  light: { en: "Light", zh: "亮色" },
  long_scrolling: { en: "Long Scrolling", zh: "长滚动" },
  masonry: { en: "Masonry", zh: "瀑布流" },
  minimal: { en: "Minimal", zh: "极简" },
  monochromatic: { en: "Monochromatic", zh: "单色调" },
  parallax: { en: "Parallax", zh: "视差滚动" },
  pastel: { en: "Pastel", zh: "粉彩" },
  retro: { en: "Retro", zh: "复古" },
  scrolling_animation: { en: "Scrolling Animation", zh: "滚动动效" },
  single_page: { en: "Single Page", zh: "单页" },
  small_type: { en: "Small Type", zh: "小字体" },
  transitions: { en: "Transitions", zh: "过渡效果" },
  typographic: { en: "Typographic", zh: "排版" },
  unusual_layout: { en: "Unusual Layout", zh: "非常规布局" },
  virtual_reality: { en: "Virtual Reality", zh: "虚拟现实" },
  webgl: { en: "WebGL", zh: "WebGL" },
};

export const siteTagMap: Record<string, { en: string; zh: string }> = {
  ...siteTagMapTypes,
  ...siteTagMapStyles,
};

export const siteTagKeys = Object.keys(siteTagMap);
