export const siteTagMapTypes: Record<string, string> = {
  agency: "Agency",
  ai: "AI",
  architecture: "Architecture",
  art: "Art",
  automotive: "Automotive",
  beauty_makeup: "Beauty makeup",
  communication: "Communication",
  community: "Community",
  crypto: "Crypto",
  design: "Design",
  desktop_app: "Desktop App",
  development: "Development",
  dress: "Dress",
  digital_product: "Digital Product",
  e_commerce: "E-commerce",
  education: "Education",
  event: "Event",
  exhibition: "Exhibition",
  fashion: "Fashion",
  finance: "Finance",
  food_drink: "Food & Drink",
  font: "Font",
  furniture: "Furniture",
  gaming: "Gaming",
  health: "Health",
  hospitality: "Hospitality",
  hr: "HR",
  interior_design: "Interior Design",
  landscaping: "Landscaping",
  legal: "Legal",
  literature: "Literature",
  magazine: "Magazine",
  manufacturing: "Manufacturing",
  marketing: "Marketing",
  medicine: "Medicine",
  mobile_app: "Mobile App",
  motion: "Motion",
  music: "Music",
  news: "News",
  nft: "NFT",
  personal: "Personal",
  pet: "Pet",
  photography: "Photography",
  plugin: "Plugin",
  podcast: "Podcast",
  political: "Political",
  portfolio: "Portfolio",
  product: "Product",
  public_relations: "Public relations",
  real_estate: "Real Estate",
  restaurant: "Restaurant",
  saas: "SaaS",
  science: "Science",
  security: "Security",
  sports: "Sports",
  technology: "Technology",
  travel: "Travel",
  web_app: "Web App",
  web3: "Web3",
};

export const siteTagMapStyles: Record<string, string> = {
  "3d": "3D",
  animation: "Animation",
  audio: "Audio",
  bento_grid: "Bento Grid",
  big_background_image: "Big Background Image",
  big_background_video: "Big Background Video",
  black_white: "Black & White",
  clean: "Clean",
  colorful: "Colorful",
  custom_cursor: "Custom Cursor",
  dark: "Dark",
  drag_drop: "Drag & Drop",
  fun: "Fun",
  gradient: "Gradient",
  grid: "Grid",
  horizontal_layout: "Horizontal Layout",
  horizontal_scrolling: "Horizontal Scrolling",
  illustrative: "Illustrative",
  infinite_scroll: "Infinite Scroll",
  interactive: "Interactive",
  large_type: "Large Type",
  light: "Light",
  light_shadow: "Light & Shadow",
  long_scrolling: "Long Scrolling",
  masonry: "Masonry",
  minimal: "Minimal",
  mimicry: "Mimicry",
  monochromatic: "Monochromatic",
  parallax: "Parallax",
  pastel: "Pastel",
  retro: "Retro",
  scrolling_animation: "Scrolling Animation",
  single_page: "Single Page",
  small_type: "Small Type",
  transitions: "Transitions",
  typographic: "Typographic",
  unusual_layout: "Unusual Layout",
  virtual_reality: "Virtual Reality",
  webgl: "WebGL",
  chinese: "Chinese",
};

export const siteTagMap: Record<string, string> = {
  ...siteTagMapTypes,
  ...siteTagMapStyles,
};

export const siteTagKeys = Object.keys(siteTagMap);
