packages:
  - apps/*
  - packages/*
catalog:
  "@orpc/server": ^1.12.2
  "@orpc/client": ^1.12.2
  "@orpc/openapi": ^1.12.2
  "@orpc/zod": ^1.12.2
  better-auth: ^1.4.5
  drizzle-orm: ^0.45.0
  "@types/pg": ^8.15.6
  dotenv: ^17.2.2
  zod: ^4.1.13
