packages:
  - apps/*
  - packages/*

catalog:
  "@orpc/client": ^1.12.2
  "@orpc/openapi": ^1.12.2
  "@orpc/server": ^1.12.2
  "@orpc/zod": ^1.12.2
  "@types/pg": ^8.15.6
  typescript: ^5
  better-auth: ^1.4.5
  date-fns: ^4.1.0
  dotenv: ^17.2.3
  drizzle-orm: ^0.45.0
  es-toolkit: ^1.43.0
  react: ^19.2.3
  resend: ^6.6.0
  zod: 4.1.13
  hono: ^4.8.2
  alchemy: ^0.82.1
  "@types/node": ^22.13.11
  "@cloudflare/workers-types": ^4.20251213.0

ignoredBuiltDependencies:
  - esbuild
  - msw
