packages:
  - apps/*
  - packages/*

catalog:
  "@orpc/client": ^1.12.2
  "@orpc/openapi": ^1.12.2
  "@orpc/server": ^1.12.2
  "@orpc/zod": ^1.12.2
  "@types/pg": ^8.15.6
  better-auth: ^1.4.5
  dotenv: ^17.2.3
  drizzle-orm: ^0.45.0
  react: ^19.2.3
  resend: ^6.6.0
  zod: ^4.1.13

ignoredBuiltDependencies:
  - esbuild
