/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgetPasswordRouteImport } from './routes/(auth)/forget-password'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appAboutRouteImport } from './routes/(app)/about'
import { Route as app404RouteImport } from './routes/(app)/404'
import { Route as appPageVersionIdRouteImport } from './routes/(app)/$pageVersionId'
import { Route as adminPanelRouteRouteImport } from './routes/(admin)/panel/route'
import { Route as adminPanelIndexRouteImport } from './routes/(admin)/panel/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appuserSubmitsRouteImport } from './routes/(app)/(user)/submits'
import { Route as appuserLikesRouteImport } from './routes/(app)/(user)/likes'
import { Route as adminPanelUsersRouteImport } from './routes/(admin)/panel/users'
import { Route as adminPanelSubmitSitesRouteImport } from './routes/(admin)/panel/submit-sites'
import { Route as adminPanelSitesRouteImport } from './routes/(admin)/panel/sites'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgetPasswordRoute = authForgetPasswordRouteImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => authRouteRoute,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appAboutRoute = appAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => appRouteRoute,
} as any)
const app404Route = app404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => appRouteRoute,
} as any)
const appPageVersionIdRoute = appPageVersionIdRouteImport.update({
  id: '/$pageVersionId',
  path: '/$pageVersionId',
  getParentRoute: () => appRouteRoute,
} as any)
const adminPanelRouteRoute = adminPanelRouteRouteImport.update({
  id: '/(admin)/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const adminPanelIndexRoute = adminPanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminPanelRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appuserSubmitsRoute = appuserSubmitsRouteImport.update({
  id: '/(user)/submits',
  path: '/submits',
  getParentRoute: () => appRouteRoute,
} as any)
const appuserLikesRoute = appuserLikesRouteImport.update({
  id: '/(user)/likes',
  path: '/likes',
  getParentRoute: () => appRouteRoute,
} as any)
const adminPanelUsersRoute = adminPanelUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => adminPanelRouteRoute,
} as any)
const adminPanelSubmitSitesRoute = adminPanelSubmitSitesRouteImport.update({
  id: '/submit-sites',
  path: '/submit-sites',
  getParentRoute: () => adminPanelRouteRoute,
} as any)
const adminPanelSitesRoute = adminPanelSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => adminPanelRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/panel': typeof adminPanelRouteRouteWithChildren
  '/$pageVersionId': typeof appPageVersionIdRoute
  '/404': typeof app404Route
  '/about': typeof appAboutRoute
  '/dashboard': typeof appDashboardRoute
  '/forget-password': typeof authForgetPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/': typeof appIndexRoute
  '/panel/sites': typeof adminPanelSitesRoute
  '/panel/submit-sites': typeof adminPanelSubmitSitesRoute
  '/panel/users': typeof adminPanelUsersRoute
  '/likes': typeof appuserLikesRoute
  '/submits': typeof appuserSubmitsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/panel/': typeof adminPanelIndexRoute
}
export interface FileRoutesByTo {
  '/$pageVersionId': typeof appPageVersionIdRoute
  '/404': typeof app404Route
  '/about': typeof appAboutRoute
  '/dashboard': typeof appDashboardRoute
  '/forget-password': typeof authForgetPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/': typeof appIndexRoute
  '/panel/sites': typeof adminPanelSitesRoute
  '/panel/submit-sites': typeof adminPanelSubmitSitesRoute
  '/panel/users': typeof adminPanelUsersRoute
  '/likes': typeof appuserLikesRoute
  '/submits': typeof appuserSubmitsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/panel': typeof adminPanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(admin)/panel': typeof adminPanelRouteRouteWithChildren
  '/(app)/$pageVersionId': typeof appPageVersionIdRoute
  '/(app)/404': typeof app404Route
  '/(app)/about': typeof appAboutRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(auth)/forget-password': typeof authForgetPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(app)/': typeof appIndexRoute
  '/(admin)/panel/sites': typeof adminPanelSitesRoute
  '/(admin)/panel/submit-sites': typeof adminPanelSubmitSitesRoute
  '/(admin)/panel/users': typeof adminPanelUsersRoute
  '/(app)/(user)/likes': typeof appuserLikesRoute
  '/(app)/(user)/submits': typeof appuserSubmitsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/(admin)/panel/': typeof adminPanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/panel'
    | '/$pageVersionId'
    | '/404'
    | '/about'
    | '/dashboard'
    | '/forget-password'
    | '/login'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/'
    | '/panel/sites'
    | '/panel/submit-sites'
    | '/panel/users'
    | '/likes'
    | '/submits'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/panel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$pageVersionId'
    | '/404'
    | '/about'
    | '/dashboard'
    | '/forget-password'
    | '/login'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/'
    | '/panel/sites'
    | '/panel/submit-sites'
    | '/panel/users'
    | '/likes'
    | '/submits'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/panel'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/(admin)/panel'
    | '/(app)/$pageVersionId'
    | '/(app)/404'
    | '/(app)/about'
    | '/(app)/dashboard'
    | '/(auth)/forget-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(auth)/verify-email'
    | '/(app)/'
    | '/(admin)/panel/sites'
    | '/(admin)/panel/submit-sites'
    | '/(admin)/panel/users'
    | '/(app)/(user)/likes'
    | '/(app)/(user)/submits'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/(admin)/panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  adminPanelRouteRoute: typeof adminPanelRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forget-password': {
      id: '/(auth)/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof authForgetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/about': {
      id: '/(app)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appAboutRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/404': {
      id: '/(app)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof app404RouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/$pageVersionId': {
      id: '/(app)/$pageVersionId'
      path: '/$pageVersionId'
      fullPath: '/$pageVersionId'
      preLoaderRoute: typeof appPageVersionIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(admin)/panel': {
      id: '/(admin)/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof adminPanelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/panel/': {
      id: '/(admin)/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof adminPanelIndexRouteImport
      parentRoute: typeof adminPanelRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(user)/submits': {
      id: '/(app)/(user)/submits'
      path: '/submits'
      fullPath: '/submits'
      preLoaderRoute: typeof appuserSubmitsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(user)/likes': {
      id: '/(app)/(user)/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof appuserLikesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(admin)/panel/users': {
      id: '/(admin)/panel/users'
      path: '/users'
      fullPath: '/panel/users'
      preLoaderRoute: typeof adminPanelUsersRouteImport
      parentRoute: typeof adminPanelRouteRoute
    }
    '/(admin)/panel/submit-sites': {
      id: '/(admin)/panel/submit-sites'
      path: '/submit-sites'
      fullPath: '/panel/submit-sites'
      preLoaderRoute: typeof adminPanelSubmitSitesRouteImport
      parentRoute: typeof adminPanelRouteRoute
    }
    '/(admin)/panel/sites': {
      id: '/(admin)/panel/sites'
      path: '/sites'
      fullPath: '/panel/sites'
      preLoaderRoute: typeof adminPanelSitesRouteImport
      parentRoute: typeof adminPanelRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appPageVersionIdRoute: typeof appPageVersionIdRoute
  app404Route: typeof app404Route
  appAboutRoute: typeof appAboutRoute
  appDashboardRoute: typeof appDashboardRoute
  appIndexRoute: typeof appIndexRoute
  appuserLikesRoute: typeof appuserLikesRoute
  appuserSubmitsRoute: typeof appuserSubmitsRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appPageVersionIdRoute: appPageVersionIdRoute,
  app404Route: app404Route,
  appAboutRoute: appAboutRoute,
  appDashboardRoute: appDashboardRoute,
  appIndexRoute: appIndexRoute,
  appuserLikesRoute: appuserLikesRoute,
  appuserSubmitsRoute: appuserSubmitsRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authForgetPasswordRoute: typeof authForgetPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgetPasswordRoute: authForgetPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface adminPanelRouteRouteChildren {
  adminPanelSitesRoute: typeof adminPanelSitesRoute
  adminPanelSubmitSitesRoute: typeof adminPanelSubmitSitesRoute
  adminPanelUsersRoute: typeof adminPanelUsersRoute
  adminPanelIndexRoute: typeof adminPanelIndexRoute
}

const adminPanelRouteRouteChildren: adminPanelRouteRouteChildren = {
  adminPanelSitesRoute: adminPanelSitesRoute,
  adminPanelSubmitSitesRoute: adminPanelSubmitSitesRoute,
  adminPanelUsersRoute: adminPanelUsersRoute,
  adminPanelIndexRoute: adminPanelIndexRoute,
}

const adminPanelRouteRouteWithChildren = adminPanelRouteRoute._addFileChildren(
  adminPanelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  adminPanelRouteRoute: adminPanelRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
