export const site = {
  url: "https://refto.one",
  name: "refto",
  siteName: "Refto",
  description: "Unleash limitless inspiration. Embrace pure simplicity.",
  keywords: [
    "refto",
    "refto.one",
    "Design",
    "Website",
    "Website Design",
    "Interaction",
    "Inspiration",
    "Design Resources",
  ],
  author: "hehehai",
  authorUrl: "https://hehehai.cn",
  githubUrl: "https://github.com/hehehai/refto",
  ogImage: "https://refto.one/images/og.jpg",
  icons: [{ rel: "icon", url: "/favicon.svg", type: "image/svg+xml" }],
  ga: "G-SHWYRC6QM5",
};
